# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: 
#
stripe_api_key: sk_test_Rh5ZYKJPb6k797ng90H5jDe0
stripe_publishable_key: pk_test_8fciVTm14BbOUj4GMxOBMFQs
#
# production:
   stripe_api_key: sk_test_Rh5ZYKJPb6k797ng90H5jDe0
   stripe_publishable_key: pk_test_8fciVTm14BbOUj4GMxOBMFQs
